#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# THIS REPOSITORY WAS AI-GENERATED by Claude (Opus 4.6) based on a snapshot of
# badek2000's live system on 2026-04-15. Review every script before running
# unattended on a new machine — it reflects one user's preferences, not a
# general-purpose installer.
# -----------------------------------------------------------------------------
#
# Orchestrator. Run with no args for the default set, or pass flags to pick modules.
#
#   ./install.sh                  # everything below
#   ./install.sh --dotfiles       # stow fish/ranger/tmux/vim/kitty
#   ./install.sh --dev            # rust, pyenv, c/c++, gh
#   ./install.sh --desktop        # firefox, vscode, moonlight, jetbrains-mono
#   ./install.sh --vscode         # vscode extensions + settings/keybindings
#   ./install.sh --wallpaper      # apply assets/background.jpg via gsettings
#   ./install.sh --fonts          # apply manifests/fonts.conf via gsettings
#   ./install.sh --gnome          # apply full dconf dump (dock, shortcuts, ...)
#   ./install.sh --snapshots      # snapper (only if root fs is btrfs)
#   ./install.sh --defaults       # chsh to fish, git config, vim as editor
#
# GitHub SSH is intentionally separate: scripts/setup-ssh-github.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$REPO_ROOT/scripts/lib.sh"
require_not_root

FAILED=()
run_step() {
  local name="$1"; shift
  log "── $name ──"
  if bash "$@"; then
    return 0
  fi
  warn "$name failed (exit $?) — continuing"
  FAILED+=("$name")
}

run_dotfiles()  { run_step dotfiles  "$REPO_ROOT/scripts/link-dotfiles.sh"; }
run_dev()       { run_step dev       "$REPO_ROOT/scripts/install-dev.sh"; }
run_desktop()   { run_step desktop   "$REPO_ROOT/scripts/install-desktop.sh"; }
run_vscode()    { run_step vscode    "$REPO_ROOT/scripts/vscode-setup.sh"; }
run_wall()      { run_step wallpaper "$REPO_ROOT/scripts/set-wallpaper.sh"; }
run_fonts()     { run_step fonts     "$REPO_ROOT/scripts/set-fonts.sh"; }
run_gnome()     { run_step gnome     "$REPO_ROOT/scripts/gnome-settings.sh"; }
run_snapshots() { run_step snapshots "$REPO_ROOT/scripts/install-snapshots.sh"; }
run_defaults()  { run_step defaults  "$REPO_ROOT/scripts/configure-defaults.sh"; }

run_base() {
  apt_update_once
  apt_install_from_file "$REPO_ROOT/manifests/apt-base.txt"
}

farewell() {
  local BOLD_RED="\033[1;31m"
  local RESET="\033[0m"
  local CYAN="\033[1;36m"
  printf "${CYAN}Welcome back, ${RESET}\n\n"
  cat <<'EOF'


    ██████╗  █████╗ ██████╗ ███████╗██╗  ██╗██████╗  ██████╗  ██████╗  ██████╗
    ██╔══██╗██╔══██╗██╔══██╗██╔════╝██║ ██╔╝╚════██╗██╔═████╗██╔═████╗██╔═████╗
    ██████╔╝███████║██║  ██║█████╗  █████╔╝  █████╔╝██║██╔██║██║██╔██║██║██╔██║
    ██╔══██╗██╔══██║██║  ██║██╔══╝  ██╔═██╗ ██╔═══╝ ████╔╝██║████╔╝██║████╔╝██║
    ██████╔╝██║  ██║██████╔╝███████╗██║  ██╗███████╗╚██████╔╝╚██████╔╝╚██████╔╝
    ╚═════╝ ╚═╝  ╚═╝╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚═════╝  ╚═════╝

EOF
  echo   "    Next steps:"
  echo   "      * Log out and back in so fish + GNOME settings take effect"
  echo   "      * GitHub SSH:  bash scripts/setup-ssh-github.sh"
  echo   "      * Launch Moonlight: flatpak run com.moonlight_stream.Moonlight"
  echo   "      * Snapshots (btrfs only): sudo snapper list"
  echo
  printf "${BOLD_RED}  !! NOTE: this repository is AI-generated. Review scripts before re-running on other machines. !!${RESET}\n\n"
  if (( ${#FAILED[@]} )); then
    printf "${BOLD_RED}  Modules that failed: ${FAILED[*]}${RESET}\n\n"
  fi
}

# Short-circuit help BEFORE any side effects.
for arg in "$@"; do
  case "$arg" in
    -h|--help) sed -n '9,23p' "$0"; exit 0 ;;
  esac
done

if [[ $# -eq 0 ]]; then
  run_base
  run_dotfiles
  run_dev
  run_desktop
  run_vscode
  run_gnome
  run_wall
  run_fonts
  run_snapshots
  run_defaults
  farewell
  exit 0
fi

run_base
for arg in "$@"; do
  case "$arg" in
    --dotfiles)  run_dotfiles ;;
    --dev)       run_dev ;;
    --desktop)   run_desktop ;;
    --vscode)    run_vscode ;;
    --wallpaper) run_wall ;;
    --fonts)     run_fonts ;;
    --gnome)     run_gnome ;;
    --snapshots) run_snapshots ;;
    --defaults)  run_defaults ;;
    *) die "unknown arg: $arg" ;;
  esac
done
farewell
